id: 6d4cfec77a2f41f4bc782b39064e64df
initial_creation_type: ocr
source_metadata:
  volumes:
    8913545315f345689ad53a1b9ad98c5b:
      base_file: v025.txt
      image_group_id: I1PD95870
      title: རྡོ་རྗེ་ཁྲོ་བོ་གཏུམ་པོ་ལྷ་ལྔ་པ་ཞེས་བྱ་བའི་དཀྱིལ་འཁོར་གྱི་ཆོ་ག།
      total_pages: 1853
      volume_number: 25
